name = "etabs-ram-floor-exporter-production"
main = "src/worker.js"
compatibility_date = "2024-09-25"

[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

[env.staging]
name = "etabs-ram-floor-exporter-staging"
[env.staging.vars]
ENVIRONMENT = "staging"

[env.production]
name = "etabs-ram-floor-exporter-production"
[env.production.vars]
ENVIRONMENT = "production"
