version: '3.8'
name: floor_exporter

services:
  app:
    container_name: floor_exporter_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ALLOWED_ORIGINS=*
    # volumes:
    #   - ./backend/data:/app/data
